### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by sambott** [sambott/PortableWikiViewer#1]
@adamhathcock - I had a little time so I restarted looking at something I hadn't touched in a couple of years. I've created an XZ reader using your implementation of LZMA. It's still pretty basic - read only stream with crc checks missing in a couple of places, but it will improve next time I get some time.

Mainly I'm just letting you know your project was useful, but feel free to use any of this if there is any interest for XZ functionality in your library.

Sam

**Comment by adamhathcock** [comment]
Thanks.  This might actually be interesting but I'm lacking a lot on the time front to do something like this.  I'll put an issue on Sharpcompress though.

**Comment by weltkante** [comment]
Be careful if you should make a writing implementation, it's not clear (to me) what the quality of the LZMA encoder in SharpCompress is. I'm probably going to update the implementation, see issue adamhathcock/sharpcompress#91, but it's going to take a while since I'm also working on completing the 7z format.

**Comment by adamhathcock** [comment]
Started https://github.com/adamhathcock/sharpcompress/pull/247
